# This is a basic workflow to help you get started with Actions

name: iantest

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Initialize AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          invitation-email-recipient: ${{ secrets.INVITATION_EMAIL_RECIPIENT }}
          aws-region: us-west-2

      - name: Start puppeteer
        run: |
          TEMP_PASSWORD="ci_X1hhY"
          echo "Temp password is $TEMP_PASSWORD"
          echo "Downloading puppeteer tests"
          git clone https://github.com/iandow/aws-media-insights-puppeteer
          cd aws-media-insights-puppeteer
          npm i puppeteer puppeteer-screenshot-tester
          docker build --tag=cas-puppeteer:latest .
          docker run --rm -v "$PWD":/usr/src/app -e WEBAPP_URL="https://dlueli904z5k8.cloudfront.net" -e TEMP_PASSWORD=$TEMP_PASSWORD cas-puppeteer:latest
