name: pr-workflow

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - development
  workflow_dispatch:
    
jobs:
  build-us-west-2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pr branch
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.sha }}

      - name: Initialize AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          invitation-email-recipient: ${{ secrets.INVITATION_EMAIL_RECIPIENT }}
          aws-region: us-west-2

      - name: Generate short sha
        run: |
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Run build script
        run: |
          cd deployment
          REGION=us-west-2
          VERSION="2.0.3"
          ./build.sh ${DIST_OUTPUT_BUCKET}-${REGION} ${VERSION} ${REGION} | tee >( awk '/Without existing MIE deployment/{getline; print}' >template )

      - name: Create stack
        run: |
          cd deployment
          TEMPLATE=$(cat template | cut -f 2 -d "'")
          rm -f template
          WEBAPP_STACK_NAME="pr${SHORT_SHA}"
          REGION=us-west-2
          EMAIL="ianwow@amazon.com"
          set -x
          aws cloudformation create-stack --stack-name $WEBAPP_STACK_NAME --template-url $TEMPLATE --region $REGION --parameters ParameterKey=AdminEmail,ParameterValue=$EMAIL --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --disable-rollback
          aws cloudformation wait stack-create-complete --stack-name $WEBAPP_STACK_NAME
          set +x

      - name: Get login credentials
        env: 
          TEMP_PASSWORD: 
        run: |
          # iterate thru objects in s3://github-test-bot, ordered by create time
          INVITATION_EMAIL=$(aws s3api list-objects-v2 --bucket "github-test-bot" --query 'sort_by(Contents, &LastModified)[0].Key' --output=text)
          aws s3 cp s3://github-test-bot/$INVITATION_EMAIL ./invitation_email
          aws s3 rm s3://github-test-bot/$INVITATION_EMAIL
          TEMP_PASSWORD=$(cat invitation_email | grep 'temporary password' | sed 's/.*password is \(.*\)<br>AWS.*/\1/')
          
      - name: Start puppeteer
        env: 
          TEMP_PASSWORD: 
        run: |
          echo "Temp password is $TEMP_PASSWORD"
          echo "Downloading puppeteer tests"
          git clone https://github.com/iandow/aws-media-insights-puppeteer
          #docker run --rm -v "$PWD":/usr/src/app -e WEBAPP_URL=$WEBAPP_URL TEMP_PASSWORD=$TEMP_PASSWORD cas-puppeteer:latest

